### ISSUE TITLE
theme color not working properly

### ISSUE THREAD

**Issue by trinib** [dstein64/gifcast#8]
background **color** don't seem to be changing properly in the dark ranges .. it outputs in black or grey shades with no color .. on the bright/white side it **does** changes its color shades.. Do not know why that happens on the dark side

**Comment by dstein64** [comment]
Thanks for reporting the issue! Can you provide a minimal cast file along with instructions for reproducing?

**Comment by trinib** [comment]
[cast file](https://github.com/dstein64/gifcast/files/8208245/demo.zip)
Recorded from [asciinema](https://github.com/asciinema/asciinema)

Methods for conversion :

1. Directly from your repo https://dstein64.github.io/gifcast/

2. Forked it on **windows** and **linux** and opened it from local storage

PS now realized did not installed

[xterm.js](https://github.com/xtermjs/xterm.js)
   
 [omggif](https://github.com/deanm/omggif)

Could this have caused issue with color code version ??? 😔😅

**Comment by dstein64** [comment]
@trinib can you provide details on which particular theme has the problem and how the rendered GIF differs from the expected output? It would be helpful for debugging if the cast file is minimal. That is, as short as possible but still showing the problem.

**Comment by dstein64** [comment]
Thanks for the details @trinib! I can reproduce the issue.

I've committed e99a1e40cca1cb8f2939c57c7b06e0e148bd7319 which fixes a bug preventing the color palette from properly being set. Force reloading [gifcast](https://dstein64.github.io/gifcast/) (e.g., with `ctrl-shift-r`) should pull the latest code to your browser.

I'll close this ticket. Please re-open and/or let me know if the update doesn't address the problem for you.

**Comment by trinib** [comment]
working thanks
